package com.example.buxiaohui.myapplication.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.buxiaohui.myapplication.bean.TestBean;
import com.example.buxiaohui.myapplication.bean.User;

import com.example.buxiaohui.myapplication.database.TestBeanDao;
import com.example.buxiaohui.myapplication.database.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testBeanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final TestBeanDao testBeanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(TestBean.class, testBeanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        testBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
